import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/component/organism/Header/Header";
import Footer from "@/component/organism/Footer";
import "../styles/globals.css";
import "leaflet/dist/leaflet.css";

export const metadata: Metadata = {
  title: "Voyanta",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        cssLayerName: "clerk",
      }}
    >
      <html lang="en">
        <body>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
